import type { Metadata } from "next";
import { Yomogi } from "next/font/google";
import "./globals.css";

const yomogiFont = Yomogi({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${yomogiFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
